version: 0.1.{build}
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore
build:
  parallel: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: AmoeGqiVQ/G6IU+QcA/DhcCoAQmAArNbi5wZDSG+hfxRwiGVlfinSdp4J4FCt3I4
  skip_symbols: false
  artifact: /.*\.nupkg/