version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - LICENSE
    - '*.md'
    - '.circleci/*'
branches:
  only:
    - master
install:
  - mkdir C:\Solidity
  - ps: Invoke-WebRequest https://github.com/ethereum/solidity/releases/download/v0.4.24/solidity-windows.zip -OutFile C:\Solidity\solc.zip
  - 7z e C:\Solidity\solc.zip
  - SET PATH=C:\Solidity;%PATH%
  - solc --version
before_build:
- ps: nuget restore
build:
  parallel: true
  verbosity: minimal
deploy:
  provider: NuGet
  api_key:
    secure: AmoeGqiVQ/G6IU+QcA/DhcCoAQmAArNbi5wZDSG+hfxRwiGVlfinSdp4J4FCt3I4
  skip_symbols: false
  artifact: /.*\.nupkg/
