version: 2
jobs:
  build:
    docker:
      - image: pzixel/solidity-dotnet:latest
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build      
      - run:
          name: Test
          command: dotnet test Solidity.Roslyn.Test