version: 2
jobs:
  build:
    docker:
      - image: pzixel/solidity-dotnet:netcore2.2
    working_directory: ~/Solidity.Roslyn
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build      
      - run:
          name: Test
          command: dotnet test Solidity.Roslyn.Test
  deploy:
    docker:
      - image: pzixel/solidity-dotnet:netcore2.2
    working_directory: ~/Solidity.Roslyn            
    steps:
      - checkout
      - run:
          name: pack Solidity.Roslyn.Core
          command: dotnet pack Solidity.Roslyn.Core --configuration=Release --include-symbols --output nupkgs
      - run:
          name: pack Solidity.Roslyn
          command: dotnet pack Solidity.Roslyn --configuration=Release --include-symbols --output nupkgs
      - run:
          name: deploy Solidity.Roslyn.Core
          command: dotnet nuget push Solidity.Roslyn.Core/nupkgs/*.nupkg -k $NUGETAPIKEY -s https://api.nuget.org/v3/index.json
      - run:
          name: deploy Solidity.Roslyn
          command: dotnet nuget push Solidity.Roslyn/nupkgs/*.nupkg -k $NUGETAPIKEY -s https://api.nuget.org/v3/index.json
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
          context: NuGet
