version: 2
jobs:
  build:
    docker:
      - image: pzixel/solidity-dotnet:latest
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build      
      - run:
          name: Test
          command: dotnet test Solidity.Roslyn.Test
  deploy:
    machine:
        enabled: true
    steps:
      - checkout
      - run:
          name: pack
          command: dotnet pack Solidity.Roslyn --configuration=Release --include-symbols --output nupkgs
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master          
            