version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    steps:
      - checkout
      - run:
          name: Install solidity
          command: git clone --depth 1 --recursive -b release https://github.com/ethereum/solidity && pushd ./solidity && cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=0 -DSTATIC_LINKING=1 && pushd ./solidity && make solc && install -s  solc/solc /usr/bin && popd && popd && rm -rf solidity
      - run:
          name: Restore
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build